name: Python Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with black
        run: |
          black --check --diff marching-squares/marching_squares
          black --check --diff cloud-mask/cloud_mask
      - name: Type check with mypy
        run: |
          mypy --strict --implicit-reexport marching-squares/marching_squares
          mypy --strict --implicit-reexport cloud-mask/cloud_mask
